var config = {
  BASE_URL: "https://api4.gamebus.eu/v2", //"https://api4.gamebus.eu/v2", //"http://192.168.0.106:8024/v2", //"https://api3.gamebus.eu/v2",
  CONFIG_ENDPOINT: "/wearables/tizen/config",
  ACITIVTY_ENDPOINT: "/activities?dryrun=false",
  SNOOZE_ENDPOINT: "/wearables/tizen/snooze",
  WIFI_INTERVAL: 300000,
  SENSOR_RECORDING: 60000,
  ALARM_PERIOD: 30,
  PPG_INTERVAL: 10,
  ACC_INTERVAL: 10,
  PEDOMETER_INTERVAL: 60000,
  TIZEN_PUSH: false,
  SYNC_STEPS: false,
  AUTH_TOKEN: "your token goes here",
};
